FROM tiangolo/uwsgi-nginx-flask:python3.6

WORKDIR /app/

# Copy and install service requirements
COPY requirements-service.txt .
RUN pip install -r ./requirements-service.txt

# Copy model requirements
COPY requirements.txt .
RUN pip install -r ./requirements.txt

# Copy code and model
COPY . .

CMD gunicorn -b 0.0.0.0:5000 service --timeout 300
